# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f55b3db6e255b811303119d5954eb9ffd470fc325ceff2458d6ec56c9a3745d1d505115496bd67cf751dd2db8694578e9b24062b009abf6f3318f29d034c76a

test:
  secret_key_base: be28fca9e7733526823be369c74ea582880f8a6b40d0d7601a7b56dac60aa3882d358baa861fbfc5553f5a65663fe6ca65c0c1fc56f78b46beb05b251f8214bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
